name: publish
on: [push]
jobs:
  publish-goodwe2mqtt-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GITHUB }}
      # - name: Build the goodwe2mqtt Docker image
      #   run: |
      #     docker build . --tag ghcr.io/marekzehra/goodwe2mqtt-docker:latest
      #     docker run ghcr.io/marekzehra/goodwe2mqtt-docker:latest
      #     docker push ghcr.io/marekzehra/goodwe2mqtt-docker:latest
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: . # use the Dockerfile in the root directory
          platforms: linux/amd64, linux/arm64 # multi-arch build
          push: true # push the image to the registry
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }} # tag the image with the branch name